### ISSUE TITLE
Minecraft just crashes after the 'essential has updated' pop-up

### ISSUE THREAD

**Issue by ViperZZ1** [DJtheRedstoner/PerspectiveModv4#14]
I'm on OSX, and it just crashes after running minecraft with perspective mod. Will look into this and I hope you do too.

**Comment by Wyvest** [comment]
can you send a crash log / latest.log in hst.sh?

**Comment by ViperZZ1** [comment]
im not that smart, how do i get a crash log / latest.log from hst.sh

**Comment by Wyvest** [comment]
> 
> 
> im not that smart, how do i get a crash log / latest.log from hst.sh

you paste the crash log and add it into hst.sh, save it, and then send the link here lol

**Comment by terminated-star** [comment]
Also getting this on linux, here is the log: https://paste.ee/p/sxtip

**Comment by DJtheRedstoner** [comment]
> 
> 
> Also getting this on linux, here is the log: https://paste.ee/p/sxtip

A mod of yours (hitdelayfix) includes an older version of mixin, which causes essential (a library that makes mod development easier) to break. Either remove hitdelayfix, or add a mod with up to date mixin (such as [betterchat](https://www.curseforge.com/minecraft/mc-mods/better-chat)).

**Comment by terminated-star** [comment]
> > Also getting this on linux, here is the log: https://paste.ee/p/sxtip
> 
> A mod of yours (hitdelayfix) includes an older version of mixin, which causes essential (a library that makes mod development easier) to break. Either remove hitdelayfix, or add a mod with up to date mixin (such as [betterchat](https://www.curseforge.com/minecraft/mc-mods/better-chat)).

That fixed it, thanks!

**Comment by ViperZZ1** [comment]
@Wyvest @DJtheRedstoner 

https://paste.ee/p/viCdQ

My crash log, from minecraft.

**Comment by DJtheRedstoner** [comment]
> 
> 
> @Wyvest @DJtheRedstoner
> 
> https://paste.ee/p/viCdQ
> 
> My crash log, from minecraft.

You are using Patcher 1.5.1 which is not compatible with essential at the moment. You have 2 options.
1. Use [perspectivemod v4.3](https://github.com/DJtheRedstoner/PerspectiveModv4/releases/tag/v4.3) until patcher 1.6 and essential officially release.
1. Use the patcher beta from [the sk1er support and beta discord.](https://discord.gg/d4KFR9H)

I will close this issue but please comment again or join [my discord](https://inv.wtf/djl) if you have further issues.
