### ISSUE TITLE
What's the point in wiping the repo?

### ISSUE THREAD

**Issue by LowSpecCorgi** [DJtheRedstoner/PerspectiveModv4#16]
Yes, I know you can check the commit history and pull the previous version. 

But there are other servers with use of freelook

Just because hypixel bad ‘banned’ it, doesn't mean it instantly becomes useless

**Comment by DJtheRedstoner** [comment]
After much deliberation I made the decision to "hide" the source code because of what people have done. Hence "this is why we can't have nice things".
