### ISSUE TITLE
Unloading

### ISSUE THREAD

**Issue by PrincessAkira** [DJtheRedstoner/PerspectiveModv4#2]
On some certain Servers *in this Screen Minesucht.net* it unloads behind and Infront of me
[https://i.imgur.com/ThlIMdo.png](url)

**Comment by DJtheRedstoner** [comment]
I was able to replicate this by looking at the ground for some time, then going into perspective mode, however the moment I move all of the chunks load. Is this the same issue or do the chunks not load at all for you?

**Comment by PrincessAkira** [comment]
So for me theyre still unloaded on move. Only on some servers. On servers like GommeHD its completly fine.

**Comment by PrincessAkira** [comment]
Im able to unload chucks by rapid movment in the Mod too ^-^

**Comment by PrincessAkira** [comment]
Any news?

**Comment by DJtheRedstoner** [comment]
I really have no idea what could cause this. If you can isolate it to a certain server software/version, I may be able to look into it further.

**Comment by PrincessAkira** [comment]
Its on all Servers, not directly some Servers anymore. 
Always when looking around fast, or looking down

**Comment by PrincessAkira** [comment]
Also. I may know why it causes this.
Since i think the Mod just Renders the Stuff behind and Infront you dont send Packets to the Server that your looking the Way.
It seems like the Labymod 3 Addon of this fixed it. Maybe Decomp it and look

**Comment by DJtheRedstoner** [comment]
The labymod addon does pretty much the same thing as my mod. The changes the chunk loading/culling are probably elsewhere in labymod. I 'm not really sure if it is the client or server unloading chunks and what can be done about it. I will look into this more.

**Comment by PrincessAkira** [comment]
Aight. Ill gladly help if ya need it

**Comment by DJtheRedstoner** [comment]
This *might* fix the issues. The fix is from Asbyth and LlamaLad7. Download it [here](https://cdn.discordapp.com/attachments/767833575185580065/768097138760220682/PerspectiveMod-4.2.jar). If it does (or doesn't) fix the issue please let me know. If you feel like you get worse performance while in perspective please also let me know.

**Comment by DJtheRedstoner** [comment]
fixed in 3cd0d242a9a631ab7a255c81a761b9a91c6d23b5
