### ISSUE TITLE
Stays toggled on Opening Chest

### ISSUE THREAD

**Issue by PrincessAkira** [DJtheRedstoner/PerspectiveModv4#3]
When you press the button for the mod *in hold mode* and open a chest, it stays locked to the position you look at, even after you close the chest.

https://i.imgur.com/Dvwvm5L.png

**Comment by PrincessAkira** [comment]
Made a Video about the issue with other issues that come with this
https://streamable.com/nfvcvq

**Comment by DJtheRedstoner** [comment]
Will fix this today.

**Comment by DJtheRedstoner** [comment]
Should be fixed, will release version 4.1 with the fix soon.
