### ISSUE TITLE
Force Perspective

### ISSUE THREAD

**Issue by MicrocontrollersDev** [DJtheRedstoner/PerspectiveModv4#4]
Going into regular F5, then pressing the mod key, then joining a new world makes it so that opening any sort of GUI forces you into F5 when in first person as can be seen here: https://youtu.be/Hpmt978StOw.

Seems like a similar issue to when it forces you out of regular F5 when opening a GUI.

**Comment by DJtheRedstoner** [comment]
Will fix soon.

**Comment by yggysusugysvugugsv** [comment]
i got this bug too

**Comment by DJtheRedstoner** [comment]
Fixed in latest release (I hope)
