### ISSUE TITLE
Perspective Resets and bugs out

### ISSUE THREAD

**Issue by 8KCoffeeWizard** [DJtheRedstoner/PerspectiveModv4#7]
**Bug:** https://youtu.be/ITc3waPBSdo
**Details:**
--> This is very similar to #4 but is not the same, because it happens _every time_ i open my inventory/gui and not only when joining worlds. 
--> Happens only in 'Hold' Mode, where it seems to reset the perspective and doesn't let me turn/move. 
--> Started happening after I got the [Skyblockcatia](https://www.curseforge.com/minecraft/mc-mods/skyblockcatia) mod and new Hytilities beta (1.2), but the issue persists even after removing them.

**Comment by DJtheRedstoner** [comment]
Try turning off Patcher better keybind handling.

**Comment by 8KCoffeeWizard** [comment]
I reinstalled the mod and that seems to fix it for now, if it occurs again I'll try that

**Comment by DJtheRedstoner** [comment]
I have this issue too (in a enviroment with no other mods). It stops happening when you open a gui. I will try to fix it.

**Comment by DJtheRedstoner** [comment]
Fixed in ab4eb74fb5af37b7eaf5e9faa95debb75721d269
